# Generated by Django 3.1.2 on 2020-10-22 21:32

import apps.params.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='nominal_current_1b',
            field=apps.params.fields.OneByteField(default=255, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AddField(
            model_name='parameter',
            name='nominal_voltage_1b',
            field=apps.params.fields.OneByteField(default=255, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)]),
        ),
    ]
