# Generated by Django 3.1.2 on 2020-10-24 09:50

import apps.params.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='dimming_curve_27_2b',
            new_name='dimming_curve_28_2b',
        ),
        migrations.AlterField(
            model_name='parameter',
            name='led_revision_1b',
            field=apps.params.fields.OneByteField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)]),
        ),
    ]
