# Generated by Django 3.1.2 on 2020-10-24 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0002_auto_20201024_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='analog_dim_freq_2b',
            new_name='digital_dim_freq_2b',
        ),
    ]
