# Generated by Django 3.1.2 on 2020-10-22 21:40

import apps.params.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0002_auto_20201022_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='dimming_curve_14_2b',
            field=apps.params.fields.TwoByteField(default=65535, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AddField(
            model_name='parameter',
            name='dimming_curve_27_2b',
            field=apps.params.fields.TwoByteField(default=65535, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AddField(
            model_name='parameter',
            name='dimming_curve_34_2b',
            field=apps.params.fields.TwoByteField(default=65535, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AddField(
            model_name='parameter',
            name='dimming_curve_41_2b',
            field=apps.params.fields.TwoByteField(default=65535, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AddField(
            model_name='parameter',
            name='dimming_curve_48_2b',
            field=apps.params.fields.TwoByteField(default=65535, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AddField(
            model_name='parameter',
            name='dimming_curve_52_2b',
            field=apps.params.fields.TwoByteField(default=65535, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AddField(
            model_name='parameter',
            name='dimming_curve_55_2b',
            field=apps.params.fields.TwoByteField(default=65535, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AddField(
            model_name='parameter',
            name='dimming_curve_66_2b',
            field=apps.params.fields.TwoByteField(default=65535, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AddField(
            model_name='parameter',
            name='flux_comp_0_1b',
            field=apps.params.fields.OneByteField(default=255, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AddField(
            model_name='parameter',
            name='flux_comp_25_1b',
            field=apps.params.fields.OneByteField(default=255, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AddField(
            model_name='parameter',
            name='flux_comp_50_1b',
            field=apps.params.fields.OneByteField(default=255, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AddField(
            model_name='parameter',
            name='flux_comp_75_1b',
            field=apps.params.fields.OneByteField(default=255, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AddField(
            model_name='parameter',
            name='flux_comp_m25_1b',
            field=apps.params.fields.OneByteField(default=255, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AddField(
            model_name='parameter',
            name='flux_comp_m50_1b',
            field=apps.params.fields.OneByteField(default=255, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AddField(
            model_name='parameter',
            name='flux_comp_max_1b',
            field=apps.params.fields.OneByteField(default=255, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)]),
        ),
    ]
