# Generated by Django 3.1.2 on 2020-10-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0003_auto_20201024_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='csv_name',
            field=models.CharField(default='default.csv', max_length=60, unique=True),
        ),
    ]
