# Generated by Django 3.1.2 on 2020-10-15 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Converter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('pid', models.IntegerField()),
                ('supplier', models.CharField(choices=[('CG', 'Connect Group'), ('SVI', 'SVI'), ('ELE', 'Elemaster'), ('PG', 'Page')], max_length=3)),
                ('conv_type', models.CharField(choices=[('LCC_1c', 'Low Cost Converter 1con'), ('LCC_2c', 'Low Cost Converter 2con'), ('FO4_1c', 'Fail Open Converter v4.1 1con'), ('FO4_2c', 'Fail Open Converter v4.1 2con'), ('HPC4', 'High Power Converter v4.x'), ('HPC5', 'High Power Converter v5.x'), ('HPC6', 'High Power Converter v6.x'), ('FO3.5_1c', 'Fail Open Converter v3.5 1con'), ('FO3.5_2c', 'Fail Open Converter v3.5 1con'), ('Unknown', 'Unknown converter')], default='Unknown', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LedCalib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledcalib_low', models.IntegerField()),
                ('ledcalib_high', models.IntegerField()),
                ('channel', models.CharField(choices=[('1', 'LED channel A - binary 001 (1)'), ('4', 'LED channel B - binary 100 (4)')], max_length=1)),
                ('conv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serial.converter')),
            ],
        ),
        migrations.CreateModel(
            name='CcrCalib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibccrlo', models.IntegerField()),
                ('calibccrhi', models.IntegerField()),
                ('channel', models.CharField(choices=[('1', '1con - one channel'), ('A', '2con - channel A'), ('B', '2con - channel B')], max_length=1)),
                ('conv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serial.converter')),
            ],
        ),
    ]
