# Generated by Django 3.1.2 on 2020-10-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='converter',
            name='remark',
            field=models.TextField(default='no remarks'),
        ),
    ]
