# Generated by Django 3.1.2 on 2020-11-05 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('MPP', 'Moly Permalloy Power'), ('HF', 'High Flux'), ('HFspec', 'High Flux special core'), ('Edge', 'Edge'), ('Kmu HF', 'Koolmu High Frequency'), ('Kmu', 'Koolmu'), ('XFlux', 'XFlux'), ('75S', '75 Series'), ('Kmu M', 'Koolmu MAX'), ('Kmu E-U-Bl', 'Koolmu E-core, U-core, block'), ('XF E-U-Bl', 'XFlux E-core, U-core, block'), ('HF EQ-LP', 'High Flux EQ & LP'), ('Kmu EQ-LP', 'Koolmu Flux EQ & LP'), ('XF EQ-LP', 'XFlux Flux EQ & LP')], max_length=10)),
                ('init_perm', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FluxFactors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.FloatField()),
                ('b', models.FloatField()),
                ('c', models.FloatField()),
                ('d', models.FloatField()),
                ('e', models.FloatField()),
                ('x', models.FloatField()),
                ('core_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='magnetics.core')),
            ],
        ),
        migrations.CreateModel(
            name='DCBiasFactors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.FloatField()),
                ('b', models.FloatField()),
                ('c', models.FloatField()),
                ('core_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='magnetics.core')),
            ],
        ),
        migrations.CreateModel(
            name='CoreLossFactors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.FloatField()),
                ('b', models.FloatField()),
                ('c', models.FloatField()),
                ('core_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='magnetics.core')),
            ],
        ),
    ]
